version: '3.7'
services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
        - backend-prod
  backend-prod:
    container_name: backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
