version: '3'
services:
  frontend:
    build: "frontend"
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
        - backend
  backend:
    build: "backend"
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
